### ISSUE TITLE
Sorting order of episodes

### ISSUE THREAD

**Issue by fhemberger** [dersphere/plugin.video.myvideo_de#10]
Please add sorting for "TV > Anime TV > Naruto", myvideo.de lists them in the wrong order:

```
Staffel 3 Folge 105
...
Staffel 3 Folge 158
Staffel 2 Folge 53
Staffel 2 Folge 54
...
Staffel 2 Folge 104
Staffel 1 Folge 1
Staffel 1 Folge 2
...
Staffel 1 Folge 103
```

**Comment by dersphere** [comment]
See commit. But keep in mind that I won't change the default sort order (playlist, which is like on the website) but added the possibility to re-sort all items by label. This results in a correct order in your case.

**Comment by fhemberger** [comment]
Wow, that was fast, Thank you!
