### ISSUE TITLE
Serien-Übersicht ist defekt

### ISSUE THREAD

**Issue by ckroehnert** [dersphere/plugin.video.myvideo_de#12]
Seit ein paar Wochen bekommt man weder bei sixx, sat.1, kabel1 noch pro7 die Übersicht angezeigt. Wenn man allerdings alle Serie auswahlt, so werden alle Serien aufgelistet.

Kann das jemand bestätigen oder liegt es an meinem xbmc?

Danke im Voraus.

**Comment by ghost** [comment]
Ist bei mir ebenfalls so.
