### ISSUE TITLE
Acquisition of support and further development

### ISSUE THREAD

**Issue by bromix** [dersphere/plugin.video.myvideo_de#14]
Hi,

is it okay, if I develop a re-imagined version of this addon? I've got some requests via kodinerds.net regarding a new MyVideo.de addon.
MyVideo released a new API which is almost identical to the API of one of my existing addons (seems to be the same dev-department ^^) but with different (and even more) content of shows and films.

Regards
bromix

**Comment by dersphere** [comment]
Hi,

what about working together? This addon has a well separated api- and presentation part.

Of course this is GPL and you can do/develop/release whatever you want, but why waste productivity? ;)

You can also write me an (german) email...

regards,
sphere

**Comment by bromix** [comment]
You've got mail ;)
