### ISSUE TITLE
can't install on eden

### ISSUE THREAD

**Issue by philklei** [dersphere/plugin.video.myvideo_de#5]
Hey,

i try to install this plugin on xmbc atv and i got this error: Dependancies not met 

i think this import is the problem:

script.module.simple.downloader' version='0.9.3'

any idea?

thx

**Comment by dersphere** [comment]
Looks like you are trying to install the frodo version on eden, how did you tried to install?

**Comment by philklei** [comment]
my problem was that i had install eden-pre not eden ^^
so everythink works fine :D 

you can close this thread

thanks for help

**Comment by dersphere** [comment]
no problem, thanks for reporting back ;)
