### ISSUE TITLE
Captain Tsubasa addon.py error

### ISSUE THREAD

**Issue by BurtCokain** [dersphere/plugin.video.myvideo_de#7]
Hi,

getting on xbmc via openelec on the rasbperry pi, an addon.py error when trying to navigate to TV/AnimeTV/Captain Tsubasa

via the search function the show is working,

would be nice if you could fix this in an update

thanks

**Comment by dersphere** [comment]
Working fine here.
I updated a new version some days ago, please check that you are using Version 0.9.5.

If you are on 0.9.5 and the issue is still present please send me your xbmc.log (debug mode not needed).

**Comment by BurtCokain** [comment]
Hi Sphere,
sorry for the trouble, i noticed that i am on the old version, thanks for the good work,

issue closed from my end

cheers
