### ISSUE TITLE
Regression: "D'Artagnan und die drei Musketiere" myvideo.de website issue

### ISSUE THREAD

**Issue by fhemberger** [dersphere/plugin.video.myvideo_de#9]
This issue was already fixed [in this commit](e32ff19408b9f3866aafdc56a3ee6257a024625e), but was reintroduced in the current version.

**Comment by dersphere** [comment]
What exactly is the issue?
TV-Show is listed correctly, all Episodes are listed correctly.

**Comment by dersphere** [comment]
Ah, now I see. Its correct in "TV -> All Shows" but wrong in "TV -> AnimeTV"...
